[supervisord]
nodaemon=true

[program:streamlit]
command=streamlit run app.py --server.port=8501 --server.address=0.0.0.0
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/streamlit.log
stderr_logfile=/app/logs/streamlit_err.log

[program:fastapi]
command=uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/fastapi.log
stderr_logfile=/app/logs/fastapi_err.log
